name: flutter_application
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  provider: ^4.3.2+2
  path_provider: ^2.0.2
  image_picker: ^0.6.7+22
  flutter_svg: ^0.20.0-nullsafety.3
  intl: ^0.16.1
  http: ^0.12.2
  shared_preferences: ^0.5.6+1

  cupertino_icons: ^1.0.0
  firebase_storage: ^7.0.0
  convex_bottom_bar: ^3.0.0
  firebase_database: ^6.0.0
  adaptive_theme: ^1.1.0
  image_picker_for_web: ^0.1.0+2
  firebase_auth: ^0.20.1
  firebase_auth_web: ^0.3.3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  toast: ^0.1.5
  timeago: ^3.1.0



flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
  assets:
     - asset/icons/

